### ISSUE TITLE
Backtest and Optimize a strategy with multiple tickers 

### ISSUE THREAD

**Issue by bwees** [kernc/backtesting.py#523] opened 2021-11-05 16:50 UTC
Is there a plan to support trading multiple tickers in a backtest? If there is already a way, does it support optimization? I want to test my entire strategy including stock identification.

**Comment by kernc** [comment] 2021-11-05 18:50
Duplicate of https://github.com/kernc/backtesting.py/issues/20.

**Closed by kernc** 2021-11-05 18:50 UTC
