### ISSUE TITLE
How to set Slippage?

### ISSUE THREAD

**Issue by MarkWh1te** [kernc/backtesting.py#142] opened 2020-09-15 11:57 UTC
### Expected Behavior
set  Slippage

### Actual Behavior
I donot know how to set   Slippage

**Comment by kernc** [comment] 2020-09-15 12:31
Ok.

But do you know how to [search](https://github.com/kernc/backtesting.py/search?q=Slippage&type=issues)? :raised_eyebrow:

**Comment by kernc** [comment] 2020-09-15 12:31
Duplicate of https://github.com/kernc/backtesting.py/issues/128.

**Closed by kernc** 2020-09-15 12:31 UTC
