### ISSUE TITLE
Can backtesting.py be used to back test a long only strategy which switches between different equities

### ISSUE THREAD

**Issue by tridgeway176** [kernc/backtesting.py#60] opened 2020-05-02 11:22 UTC
### Expected Behavior
From a basket of equities the strategy buys the equity at 100% with best momentum.
If the equity with best momentum changes the previously equity is sold and fully invested in the equity with best momentum.

**Comment by kernc** [comment] 2020-05-02 17:24
No. Unfortunately, backtesting.py only supports testing on a single equity at a time. For your use case, maybe try [`bt`](https://pmorissette.github.io/bt/) and its [`bt.algos.SelectMomentum`](https://pmorissette.github.io/bt/bt.html#bt.algos.SelectMomentum).

**Comment by kernc** [comment] 2020-07-15 12:57
Duplicate of issue https://github.com/kernc/backtesting.py/issues/20.

**Closed by kernc** 2020-07-15 12:57 UTC
Labels: question
