### ISSUE TITLE
Backtest is closing trades at last candle

### ISSUE THREAD

**Issue by replacementAI** [kernc/backtesting.py#535] opened 2021-11-17 15:46 UTC
### Expected Behavior
Number of trades shouldn't account for open trade at last candle.
._trades shouldnt return an ExitBar, ExitPrice, PnL, ReturnPct, ExitTime, and a Duration for open trade.

### Actual Behavior
Number  of trades accounts for open trade at last candle.
._trades returns an ExitBar, ExitPrice, PnL, ReturnPct, ExitTime, and a Duration for an open trade.

### Steps to Reproduce

[prediction (2).csv](https://github.com/kernc/backtesting.py/files/7555961/prediction.2.csv)
[prediction (1).csv](https://github.com/kernc/backtesting.py/files/7555962/prediction.1.csv)

1. Set prediction (1).csv as Data
2. Run it through bt.run
3. Last trade should be open since forecastedClose > Open
4. Set prediction (2).csv as Data
5. Run it through bt.run
6. Last trade is closed as it should be since forecastedClose < Open

ALTERNATIVELY, use any strategy that should have an open trade at the last candle.

```python

from backtesting import Strategy, Backtest
class MyStrategy(Strategy):
    Data = prediction
    
    def init(self):
        super().init()
    
    def next(self):
        if  self.data.forecastedClose>self.data.Open:
            self.buy()
        elif self.data.forecastedClose<self.data.Open:
            self.position.close()

bt = Backtest(prediction, MyStrategy, cash=1000, trade_on_close=False)
stats=bt.run()
stats
stats._trades
```

### Additional info

![image](https://user-images.githubusercontent.com/55959390/142233019-80e13b8a-4a38-46ee-97e8-d8283fcdea56.png)
._trades output for prediction 1

![image](https://user-images.githubusercontent.com/55959390/142232698-ead8f6c8-d2cb-4a2b-bea6-755c8741f051.png)
._trades output for prediction 2

- Backtesting version: 0.3.2

**Comment by kernc** [comment] 2022-02-21 04:42
Duplicate of https://github.com/kernc/backtesting.py/issues/343.

**Closed by kernc** 2022-02-21 04:42 UTC
