### ISSUE TITLE
Buy at the open price and sell at the close price?

### ISSUE THREAD

**Issue by reyahmadi** [kernc/backtesting.py#652] opened 2022-05-26 05:39 UTC
Is it possible to buy at the open price and sell at the close price? As far as I understood, we can only use one of these prices for the trades and it has to be determined before running.

**Comment by kernc** [comment] 2022-05-26 14:57
Duplicate of https://github.com/kernc/backtesting.py/issues/249.

**Closed by kernc** 2022-05-26 14:57 UTC
