### ISSUE TITLE
Multiple assets (not pair trading)

### ISSUE THREAD

**Issue by lorrp1** [kernc/backtesting.py#270] opened 2021-03-05 10:01 UTC
Is there a way to add another asset? I’d like to trade one asset most of the time and use another as "hedge", I’d use 2 asset at the same time

I have seen there was a question about pair trading but instrument1/instrument2 isn’t what I’m looking for

**Comment by kernc** [comment] 2021-03-05 14:20
Duplicate of https://github.com/kernc/backtesting.py/issues/20.

**Closed by kernc** 2021-03-05 14:20 UTC

**Comment by lorrp1** [comment] 2021-03-05 14:47
@kernc hello, I still don’t understand, another user said it’s possible but I’d need to iterate in for each instrument,while you just answered no. 

Anyway I could simply do like the user suggested and then sort of average the results probably
