### ISSUE TITLE
Beginner's question - no Plot, please help

### ISSUE THREAD

**Issue by Helliott31** [kernc/backtesting.py#922] opened 2023-02-25 18:30 UTC
Hello, I'm very new to Python and backtesting.py, I'm sure this error has been sorted but I can't find where.
I'm simply trying to compute the example with the exact code given with the package
I get an empty plot as a result.

### Expected Behavior
Get the same plot as in example

### Actual Behavior
White screen with axis on the right of the html file

I also get the following warning:
BokehDeprecationWarning: Passing lists of formats for DatetimeTickFormatter scales was deprecated in Bokeh 3.0. Configure a single string format for each scale
/Users/michael/PycharmProjects/Carry_optimizer/venv/lib/python3.11/site-packages/backtesting/_plotting.py:250: UserWarning: DatetimeFormatter scales now only accept a single format. Using the first provided: '%d %b'
  formatter=DatetimeTickFormatter(days=['%d %b', '%a %d'],

### Steps to Reproduce

1.Run the following code

```python
Run the following code:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover

from backtesting.test import SMA, GOOG


class SmaCross(Strategy):
    def init(self):
        price = self.data.Close
        self.ma1 = self.I(SMA, price, 10)
        self.ma2 = self.I(SMA, price, 20)

    def next(self):
        if crossover(self.ma1, self.ma2):
            self.buy()
        elif crossover(self.ma2, self.ma1):
            self.sell()


bt = Backtest(GOOG, SmaCross, commission=.002,
              exclusive_orders=True)
stats = bt.run()
print(stats)
bt.plot()
python code goes here

```

### Additional info

- Backtesting version: 0.3.3  
- `bokeh.3.0.3`
- OS: MacOS 12.5

**Comment by kernc** [comment] 2023-02-25 18:37
Duplicate of https://github.com/kernc/backtesting.py/issues/803.

**Closed by kernc** 2023-02-25 18:37 UTC

**Comment by Helliott31** [comment] 2023-02-25 18:47
Thanks!!On 25 Feb 2023, at 18:37, kernc ***@***.***> wrote:﻿
Duplicate of #803.
