### ISSUE TITLE
Total signal 132 but trade 110. Lost 22 trade why?

### ISSUE THREAD

**Issue by vnvdev** [kernc/backtesting.py#819] opened 2022-11-25 12:41 UTC
Total signal : 132
Start                                     0.0
End                                    1999.0
Duration                               1999.0
Exposure Time [%]                        67.6
Equity Final [$]                   2674.95512
Equity Peak [$]                    3848.32419
Return [%]                         -10.834829
Buy & Hold Return [%]              -11.777393
Return (Ann.) [%]                         0.0
Volatility (Ann.) [%]                     NaN
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                              0.0
Max. Drawdown [%]                  -65.582658
Avg. Drawdown [%]                  -10.821976
Max. Drawdown Duration                 1417.0
Avg. Drawdown Duration             141.666667
# Trades                                110.0
Win Rate [%]                        36.363636
Best Trade [%]                       2.605783
Worst Trade [%]                     -1.270857
Avg. Trade [%]                       0.021787
Max. Trade Duration                      94.0
Avg. Trade Duration                 15.045455

**Comment by kernc** [comment] 2022-11-25 16:58
Duplicate of https://github.com/kernc/backtesting.py/issues/732.

**Closed by kernc** 2022-11-25 16:58 UTC
