### ISSUE TITLE
bt.run() raise no error, yet return nothing 

### ISSUE THREAD

**Issue by yyhono** [kernc/backtesting.py#13] opened 2019-07-22 13:33 UTC
I copy and run the SMAcross example exactly from user guide, still I got nothing returned, no statistics, no chart. I run the code on Spyder. What might be the problem? Would you pls advise?

**Comment by kernc** [comment] 2019-08-01 23:44
Duplicate of, or strongly related to, issue #5.

**Closed by kernc** 2019-08-01 23:44 UTC
Labels: duplicate
