### ISSUE TITLE
How to transfer user-defined variable to user-defined strategy class [Duplicate question due to network problem]

### ISSUE THREAD

**Issue by zhixwang** [kernc/backtesting.py#138] opened 2020-09-09 21:06 UTC
Hi, sorry that I'm not very familiar with this nice tool yet.

I defined a strategy class called `Parcel`. I want to pass a variable (for example, named as `input_variable`) when a new instance of `Parcel` is created. 

I tried to write as:
```
class Parcel(SignalStrategy,
               TrailingStrategy):
    
    def init(self, input_variable = 10):
        super().init()
        print(input_variable )
        ....


bt = Backtest(GOOGL, Parcel, input_variable = 5, cash = 10000, commission=.002)
```

The error is:
```
TypeError: __init__() got an unexpected keyword argument 'input_variable '
```

I think this might due to that I don't really understand the meaning of **`, *, ` (the star sign)**  in the reference manual:
```
class Backtest
(
data, strategy, *, cash=10000, commission=0.0, margin=1.0, trade_on_close=False, hedging=False, exclusive_orders=False)
```

How should I correct my code properly?

Thanks a lot!

**Comment by zhixwang** [comment] 2020-09-09 21:12
Sorry for the duplicate questions due to my network problem. I close this issue leaving the other one open. Please feel free to delete this duplicate question.

**Comment by kernc** [comment] 2020-09-09 21:20
Duplicate of https://github.com/kernc/backtesting.py/issues/139.

**Closed by kernc** 2020-09-09 21:20 UTC
