### ISSUE TITLE
Plotting error

### ISSUE THREAD

**Issue by jamhot1** [kernc/backtesting.py#55] opened 2020-03-28 21:36 UTC
### Expected Behavior
load Bokeh and open a window in chrome with plot

### Actual Behavior
unexpected attribute 'callback' to Range1d, similar attributes are js_event_callbacks

### Steps to Reproduce

tested with tutorial SMA cross example

### Additional info

- Backtesting version:  latest (17)

**Comment by kernc** [comment] 2020-03-28 22:07
Duplicate of https://github.com/kernc/backtesting.py/issues/48. Fixed in https://github.com/kernc/backtesting.py/commit/56b315037f52f029699225e73cf57951030a3ea9.

What do you mean with:

> Backtesting version: latest (17)

Please try to update:

```bash
pip install -U backtesting>=0.1.7
```

**Closed by kernc** 2020-03-28 22:07 UTC

**Comment by jamhot1** [comment] 2020-03-28 22:22
Sorry! meant 0.1.7. was my attempt at shorthand. I tried an update before I posted

**Comment by kernc** [comment] 2020-03-28 22:43
I assumed as much, but this unfortunately doesn't make sense. There is no [`callback` in this codebase](https://github.com/kernc/backtesting.py/search?q=callback&unscoped_q=callback) any longer.

Can you confirm that it's one and the same Python environment where pip and your example code are run?

**Comment by jamhot1** [comment] 2020-03-29 09:02
Hi. slightly confused by this myself. It was running fine yesterday. Then started firing this issue out of the blue. I since restarted jupiter and now running fine again???? Sorry to have wasted your time buddy
