### ISSUE TITLE
Different calculation when adding unused indicator

### ISSUE THREAD

**Issue by Alex-CodeLab** [kernc/backtesting.py#165] opened 2020-10-31 14:29 UTC
### Steps to Reproduce
When adding a extra SMA to the example (from the tutorial), the outcome is different, as it makes 1 less trade. 
Even though this is `self.sma3` is never used anywhere.   (97trades vs 98 trades).
As far as I know, this only happens when SMA's  10, 19 , (20) are used .
 
```
class SmaCross(Strategy):
    # Define the two MA lags as *class variables*
    # for later optimization
    n1 = 10
    n2 = 19
    n3 = 20
        
    def init(self):
        # Precompute the two moving averages
        self.sma1 = self.I(SMA, self.data.Close, self.n1)
        self.sma2 = self.I(SMA, self.data.Close, self.n2)
        self.sma3 = self.I(SMA, self.data.Close, self.n3)
```

### Additional info

- Backtesting version: 0.?.?

**Comment by kernc** [comment] 2020-10-31 18:59
By the sound of it, duplicate of https://github.com/kernc/backtesting.py/issues/158.

**Closed by kernc** 2020-10-31 18:59 UTC
