### ISSUE TITLE
Javascript Error: Can't plot and graph doesn't show

### ISSUE THREAD

**Issue by anthonywah** [kernc/backtesting.py#804] opened 2022-11-10 17:02 UTC
I constructed a backtest in the following way:

```python
def bb_ub(df_close, n, n_std):
    r = pd.Series(df_close).rolling(n)
    return r.mean() + (n_std * r.std())

def bb_m(df_close, n):
    return pd.Series(df_close).rolling(n).mean()

def bb_lb(df_close, n, n_std):
    r = pd.Series(df_close).rolling(n)
    return r.mean() - (n_std * r.std())

class BB(Strategy):
    
    # Strategy variables
    N = 20
    N_STD = 2
    
    def init(self):
        self.ub = self.I(bb_ub, self.data['Close'], self.N, self.N_STD)
        self.m = self.I(bb_m, self.data['Close'], self.N)
        self.lb = self.I(bb_lb, self.data['Close'], self.N, self.N_STD)

    def next(self):
        close = self.data['Close'][-1]
        if crossover(self.data['Close'], self.ub):
            self.sell(sl=1.05 * close, tp=0.95 * close)
        
        elif crossover(self.data['Close'], self.lb):
            self.buy(sl=0.95 * close, tp=1.05 * close)

bt = Backtest(
    df, 
    BB, 
    cash=10_000_000.0, 
    commission=.002, 
    exclusive_orders=True
)
stats = bt.run()
```

where df looks like:

<img width="411" alt="スクリーンショット 2022-11-11 午前12 55 10" src="https://user-images.githubusercontent.com/28438114/201157962-21046165-ae55-42ba-8ac7-34a43f19a0a6.png">

and the backtest results look likt:

<img width="356" alt="スクリーンショット 2022-11-11 午前12 55 36" src="https://user-images.githubusercontent.com/28438114/201159085-90998ef7-b47f-4571-8ebf-8a71662ea233.png">

And tried to plot the backtest graph by:

```python
j = bt.plot()
```

However it showed me the following error

```
Javascript Error: unable to decode an object of type 'Row'
```

<img width="455" alt="スクリーンショット 2022-11-11 午前12 56 14" src="https://user-images.githubusercontent.com/28438114/201158209-a00735b0-9fb9-4f61-8c93-5c6f2cc0510f.png">

- Backtesting version: 0.3.3
- bokeh version: 2.4.3 (Saw #803 so installed 2.4.3 instead)

**Comment by anthonywah** [comment] 2022-11-10 17:07
Btw extraordinary work. Thank you a lot for making backtesting more reachable to every one =)

**Comment by melgor** [comment] 2022-11-16 15:53
I had the same issue. I removed bokeh from base and project environment. Then install Bokeh=2.4.3 and make sure that in jupyter lab BokehJS 2.4.3 is loaded (previously I reinstalled bokeh to 2.4.3 but still BokehJS was 3.0.1)

![Screenshot 2022-11-16 at 16 51 56](https://user-images.githubusercontent.com/2587438/202228432-215ac2cb-9f27-473d-8395-cddd35db2d16.png)

**Comment by kernc** [comment] 2022-12-13 14:16
Let's consider this a duplicate of https://github.com/kernc/backtesting.py/issues/803.

**Closed by kernc** 2022-12-13 14:16 UTC
