### ISSUE TITLE
plot with different packages?

### ISSUE THREAD

**Issue by jamhot1** [kernc/backtesting.py#176] opened 2020-11-09 13:28 UTC
Is it possible to plot with alternative libraries?

**Comment by kernc** [comment] 2020-11-09 15:28
Is this a duplicate of https://github.com/kernc/backtesting.py/issues/94? :smile:

> Is it possible to plot with alternative libraries?

Why?

**Comment by jamhot1** [comment] 2020-11-09 15:33
I see that it had been updated. is it not possible to simply import lib of choice and plot values of the data?

**Comment by kernc** [comment] 2020-11-09 16:08
Yeah, I don't think that's how programs work, for the moment still at least. :sweat_smile: 

This is [the plotting code](https://github.com/kernc/backtesting.py/blob/252cabdf15fd8827560393cc4eb64d48a5a66bd9/backtesting/_plotting.py). In order to use an alternative "plotting framework", someone would have to [port](https://en.wikipedia.org/wiki/Porting) it.

You're invited to share/show what you come up with!

**Closed by kernc** 2020-11-09 16:08 UTC

**Comment by kernc** [comment] 2020-11-10 20:05
@jamhot1 _Why_, though? What are you missing?

**Comment by FilJed** [comment] 2022-11-24 14:02
Just wanted to mention, that bokeh backend is not working properly in vs code jupyter. It doesn't plot anything inline.
Which is kind of a bummer.

However, there is some workaround:
https://github.com/bokeh/bokeh/issues/10765
