### ISSUE TITLE
The example code(SMA crossover) don't open position in BTCUSDT sometime

### ISSUE THREAD

**Issue by kenhawk9527** [kernc/backtesting.py#160] opened 2020-10-25 10:13 UTC
I was trying to do backtesting in BTCUSDT Binance by example strategy, sma crossover.
collecting history bar in 1hr since 2020/07/15 12:00 couldn't work in example strategy,
the following are the raw data and HTML file. 

### working file.
[raw dataFrame](https://github.com/kenhawk9527/backtesting/blob/main/BTC-USDT1h_Binance_worked.txt)
[HTML](https://github.com/kenhawk9527/backtesting/blob/main/SmaCross_worked.html)

### issued file.
[raw dataFrame_issued](https://github.com/kenhawk9527/backtesting/blob/main/BTC-USDT1h_Binance_issued.txt)
[HTML_issued](https://github.com/kenhawk9527/backtesting/blob/main/SmaCross_issue.html)

### Additional info

- Backtesting version: 0.2.3   

thx for your reading.

**Comment by kernc** [comment] 2020-10-25 12:45
Duplicate of https://github.com/kernc/backtesting.py/issues/151#issuecomment-703281448. Addressed in https://github.com/kernc/backtesting.py/commit/c5cd1b3557c72b3ea2a14207ff9e076ec41a1560.

**Closed by kernc** 2020-10-25 12:45 UTC

**Comment by kenhawk9527** [comment] 2020-10-25 13:00
thx. the issue was fixed by increase the initial cash.
