### ISSUE TITLE
Negative commission

### ISSUE THREAD

**Issue by JoeSham** [kernc/backtesting.py#301] opened 2021-04-04 16:50 UTC
Hi, I see the library does not allow negative commissions (rebates):
https://github.com/kernc/backtesting.py/blob/master/backtesting/backtesting.py#L667

Some exchanges (i.e. Bybit) offer that for Maker orders. Could you please add this possibility?

**Comment by kernc** [comment] 2021-04-04 17:06
Duplicate of #248.

**Closed by kernc** 2021-04-04 17:06 UTC
