### ISSUE TITLE
self.sell error, but the error says "Long position required ...

### ISSUE THREAD

**Issue by tahubusuk** [kernc/backtesting.py#863] opened 2023-01-02 23:44 UTC
### Steps to Reproduce

1.
2.
3.

```python

python code goes here

```

### Additional info

- Backtesting version: 0.?.?   
- `bokeh.__version__`:
- OS:

**Comment by kernc** [comment] 2023-01-03 01:39
Duplicate of https://github.com/kernc/backtesting.py/issues/864.

**Closed by kernc** 2023-01-03 01:39 UTC
