### ISSUE TITLE
Q: How to backtesting Micro-Futures

### ISSUE THREAD

**Issue by KingKnecht** [kernc/backtesting.py#313] opened 2021-04-23 19:44 UTC
When trading Micro-Futures
1. there is a fixed commission say 0.77€/contract. As I understand it's not possible to have fixed commission with this framework?
2. one tick (0.25) in price  is worth 1.25€. Is there a way to simulate this?

Thx

**Comment by kernc** [comment] 2021-04-24 19:43
> 1. there is a fixed commission say 0.77€/contract. As I understand it's not possible to have fixed commission with this framework?

Indeed, duplicate of https://github.com/kernc/backtesting.py/issues/113. Something simple adversarial as this might work:
```py
commission = ceil(0.77 / data.Close.mean() * 1e3) / 1e3
```

> 2. one tick (0.25) in price  is worth 1.25€. Is there a way to simulate this?

I don't quite get it. One tick (1/4) in price is worth 1.25€? So four ticks (4/4) signify a move of 5€? Can you show a sample of your data?

**Comment by KingKnecht** [comment] 2021-04-24 19:59
> I don't quite get it. One tick (1/4) in price is worth 1.25€? So four ticks (4/4) signify a move of 5€? Can you show a sample of your data?

Exactly. 
![image](https://user-images.githubusercontent.com/4339172/115971368-5491c600-a548-11eb-93b1-2dee9d203abb.png)

[CMC](https://www.cmegroup.com/trading/equity-index/us-index/micro-e-mini-sandp-500_contract_specifications.html)

**Comment by KingKnecht** [comment] 2021-04-24 20:10
Here are same trading examples. Red lined example is 2 ticks ( tick size 0.25) which is then 2.50€.
![image](https://user-images.githubusercontent.com/4339172/115971641-e77f3000-a549-11eb-8373-c69fc01e7297.png)

**Comment by kernc** [comment] 2021-04-25 01:04
If you get 5€ per every unit of price, seems to me simply multiplying `data` by 5 should do it.

**Closed by kernc** 2021-04-25 01:04 UTC
Labels: question
